// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB75XHJDDBsA9B88CN_mPJhs9ZwOZxpvQo',
    appId: '1:634213867723:web:2dbe9822b97512a0f9bb4e',
    databaseURL: "https://tibatrade-de4a9-default-rtdb.firebaseio.com",
    messagingSenderId: '634213867723',
    projectId: 'tibatrade-de4a9',
    authDomain: 'tibatrade-de4a9.firebaseapp.com',
    storageBucket: 'tibatrade-de4a9.appspot.com',
    measurementId: 'G-EBV7Z1119J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLpMc6eUyCuv55UcCUy74yw2J83kkBMRI',
    appId: '1:634213867723:android:2091f3126a96e59ef9bb4e',
    messagingSenderId: '634213867723',
    projectId: 'tibatrade-de4a9',
    storageBucket: 'tibatrade-de4a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgD6iZPkjg7Ux2S3WVJgxMRBdbTNCOYpA',
    appId: '1:634213867723:ios:b9d7603cacb1fec0f9bb4e',
    messagingSenderId: '634213867723',
    projectId: 'tibatrade-de4a9',
    storageBucket: 'tibatrade-de4a9.appspot.com',
    iosBundleId: 'com.app.tibatrade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgD6iZPkjg7Ux2S3WVJgxMRBdbTNCOYpA',
    appId: '1:634213867723:ios:b9d7603cacb1fec0f9bb4e',
    messagingSenderId: '634213867723',
    projectId: 'tibatrade-de4a9',
    storageBucket: 'tibatrade-de4a9.appspot.com',
    iosBundleId: 'com.app.tibatrade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB75XHJDDBsA9B88CN_mPJhs9ZwOZxpvQo',
    appId: '1:634213867723:web:f5cfc3e65522c894f9bb4e',
    messagingSenderId: '634213867723',
    projectId: 'tibatrade-de4a9',
    authDomain: 'tibatrade-de4a9.firebaseapp.com',
    storageBucket: 'tibatrade-de4a9.appspot.com',
    measurementId: 'G-QC2QCPRZ4D',
  );
}
